version: '3'

services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
            PGDATA: /db/postgres/data
        ports: [5432]
        volumes: 
            - /db/postgres/data:/db/postgres/data
